[build-system]
requires = ["setuptools>=61.0"]
build-backend = "setuptools.build_meta"

[project]
name = "grid-minion"
version = "0.4.5"
description = "Cliente no oficial de Python para las APIs de GRID (League of Legends)"
readme = "README.md"
requires-python = ">=3.8"
authors = [
  { name = "Iznardo", email = "contact@f1re.es" },
]
classifiers = [
    "Programming Language :: Python :: 3",
    "License :: OSI Approved :: MIT License",
    "Operating System :: OS Independent",
]
dependencies = [
    "requests>=2.28.0",
]

[project.optional-dependencies]
dev = [
    "python-dotenv>=1.0.0",
    "build",
    "twine",
]
test = [
    "python-dotenv>=1.0.0",
]

[project.urls]
"Homepage" = "https://github.com/Iznardo/grid-minion"

[tool.setuptools.packages.find]
where = ["src"]
